"""
Realistic static CRM mock data.

Field names follow CRM camelCase conventions intentionally to demonstrate
that the integration layer must transform them into the internal snake_case schema.
"""

CUSTOMERS = [
    {
        "customerId": "CRM-CUST-001",
        "fullName": "Alice Johnson",
        "emailAddress": "alice.johnson@acmecorp.com",
        "phoneNumber": "+1-555-0101",
        "companyName": "Acme Corporation",
        "accountStatus": "active",
        "billingAddress": {
            "street": "123 Commerce Blvd",
            "line2": "Suite 400",
            "city": "New York",
            "state": "NY",
            "country": "US",
            "zip": "10001",
        },
        "createdAt": "2023-06-15T09:00:00Z",
    },
    {
        "customerId": "CRM-CUST-002",
        "fullName": "Bob Martinez",
        "emailAddress": "bob.martinez@globex.io",
        "phoneNumber": "+1-555-0202",
        "companyName": "Globex Industries",
        "accountStatus": "active",
        "billingAddress": {
            "street": "456 Industrial Pkwy",
            "city": "Austin",
            "state": "TX",
            "country": "US",
            "zip": "78701",
        },
        "createdAt": "2023-07-20T14:30:00Z",
    },
    {
        "customerId": "CRM-CUST-003",
        "fullName": "Carol Chen",
        "emailAddress": "carol.chen@initech.com",
        "phoneNumber": "+1-555-0303",
        "companyName": "Initech Solutions",
        "accountStatus": "active",
        "billingAddress": {
            "street": "789 Tech Drive",
            "city": "San Francisco",
            "state": "CA",
            "country": "US",
            "zip": "94105",
        },
        "createdAt": "2023-08-05T11:15:00Z",
    },
    {
        "customerId": "CRM-CUST-004",
        "fullName": "David Kim",
        "emailAddress": "david.kim@umbrellacorp.net",
        "phoneNumber": "+1-555-0404",
        "companyName": "Umbrella Corp",
        "accountStatus": "inactive",
        "billingAddress": {
            "street": "321 Raccoon City Rd",
            "city": "Chicago",
            "state": "IL",
            "country": "US",
            "zip": "60601",
        },
        "createdAt": "2023-09-01T08:00:00Z",
    },
    {
        "customerId": "CRM-CUST-005",
        "fullName": "Emily Patel",
        "emailAddress": "emily.patel@wayneenterprises.com",
        "phoneNumber": "+1-555-0505",
        "companyName": "Wayne Enterprises",
        "accountStatus": "active",
        "billingAddress": {
            "street": "1 Wayne Tower",
            "city": "Gotham",
            "state": "NJ",
            "country": "US",
            "zip": "07001",
        },
        "createdAt": "2023-10-10T16:45:00Z",
    },
]

ORDERS = [
    {
        "orderId": "CRM-ORD-1001",
        "customerId": "CRM-CUST-001",
        "orderNumber": "ORD-2024-1001",
        "status": "shipped",
        "totalAmount": 1250.00,
        "currency": "USD",
        "orderDate": "2024-01-10T10:00:00Z",
        "notes": "Priority shipping requested",
    },
    {
        "orderId": "CRM-ORD-1002",
        "customerId": "CRM-CUST-001",
        "orderNumber": "ORD-2024-1002",
        "status": "delivered",
        "totalAmount": 875.50,
        "currency": "USD",
        "orderDate": "2024-01-25T09:30:00Z",
        "notes": None,
    },
    {
        "orderId": "CRM-ORD-1003",
        "customerId": "CRM-CUST-002",
        "orderNumber": "ORD-2024-1003",
        "status": "processing",
        "totalAmount": 3400.00,
        "currency": "USD",
        "orderDate": "2024-02-05T14:00:00Z",
        "notes": "Bulk order — verify stock before confirming",
    },
    {
        "orderId": "CRM-ORD-1004",
        "customerId": "CRM-CUST-003",
        "orderNumber": "ORD-2024-1004",
        "status": "pending",
        "totalAmount": 520.75,
        "currency": "USD",
        "orderDate": "2024-02-15T11:00:00Z",
        "notes": None,
    },
    {
        "orderId": "CRM-ORD-1005",
        "customerId": "CRM-CUST-004",
        "orderNumber": "ORD-2024-1005",
        "status": "cancelled",
        "totalAmount": 199.99,
        "currency": "USD",
        "orderDate": "2024-02-20T16:00:00Z",
        "notes": "Customer requested cancellation",
    },
    {
        "orderId": "CRM-ORD-1006",
        "customerId": "CRM-CUST-005",
        "orderNumber": "ORD-2024-1006",
        "status": "shipped",
        "totalAmount": 7800.00,
        "currency": "USD",
        "orderDate": "2024-03-01T08:00:00Z",
        "notes": "Enterprise contract order",
    },
]
