# c-encryption/Makefile
CC = gcc
CFLAGS = -Wall -O2

all: encryption_module

encryption_module: encryption_module.c
	$(CC) $(CFLAGS) -o encryption_module encryption_module.c

clean:
	rm -f encryption_module
