"""Liquidation-trigger spread capture detector.

Detects opportunities when a synthetic liquidation event depresses venue A's
bid below the true mid by more than a configurable threshold.

Predicate:
    liq_capture := (true_mid - venue_a_bid_post_liq) / true_mid * 10000 > threshold_bps
    Only evaluated when has_liquidation is True for the current step.

Value estimation (heuristic):
    estimated_value_bps = (true_mid - venue_a_bid) / true_mid * 10000 - estimated_cost_bps

The opportunity is to buy at the depressed bid, expecting mean-reversion.
This is a synthetic event generated by the simulator.
"""

from execsim.detectors.base import (
    DetectedOpportunity,
    MarketState,
    OpportunityKind,
    SideKind,
)


class LiquidationDetector:
    """Detect liquidation-trigger spread capture opportunities on venue A."""

    def __init__(self, threshold_bps: float, estimated_cost_bps: float):
        """
        Args:
            threshold_bps: Minimum depression in bps to flag.
            estimated_cost_bps: Assumed execution cost in bps (heuristic).
        """
        if threshold_bps < 0:
            raise ValueError(f"threshold_bps must be >= 0, got {threshold_bps}")
        if estimated_cost_bps < 0:
            raise ValueError(f"estimated_cost_bps must be >= 0, got {estimated_cost_bps}")
        self.threshold_bps = threshold_bps
        self.estimated_cost_bps = estimated_cost_bps

    def detect(self, state: MarketState) -> list[DetectedOpportunity]:
        """Check for liquidation-trigger spread capture.

        Only fires when a liquidation event is active at this step.

        Args:
            state: Current market state.

        Returns:
            List with at most one opportunity if liquidation conditions met.
        """
        if not state.has_liquidation:
            return []

        mid = state.true_mid
        bid_a = state.venue_a_book.best_bid
        depression = mid - bid_a
        threshold_abs = self.threshold_bps * mid / 10000.0

        if depression <= threshold_abs:
            return []

        edge_bps = depression / mid * 10000.0
        value_bps = edge_bps - self.estimated_cost_bps

        if value_bps <= 0:
            return []

        return [
            DetectedOpportunity(
                kind=OpportunityKind.liquidation,
                side=SideKind.buy,
                estimated_value_bps=value_bps,
                edge_bps=edge_bps,
                arrival_mid=mid,
                detail={
                    "venue": "venue_a",
                    "depressed_bid": bid_a,
                    "true_mid": mid,
                    "depression_bps": edge_bps,
                },
            )
        ]
