"""Generate the synthetic public-sector corpus on disk.

Three documents are produced — a federal grant program announcement, a small
agency procurement notice, and a draft policy memo — each with realistic
section structure, tables, and prose so the retrieval pipeline has actual
text to chunk and embed.

Generated bytes are deterministic across runs (no timestamps in content, no
random IDs) so the SHA256 of each PDF is stable. Idempotency in `seed_data`
relies on that.
"""
from __future__ import annotations

import io
from dataclasses import dataclass

from reportlab import rl_config
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# Force ReportLab to omit creation timestamp + per-render document ID so
# repeated renders of identical content produce byte-identical PDFs (and
# therefore identical SHA256 hashes — the dedupe path in document_service
# depends on this).
rl_config.invariant = 1


@dataclass(frozen=True)
class SamplePDF:
    filename: str
    title: str
    bytes_: bytes


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "DocTitle",
            parent=base["Title"],
            fontName="Times-Bold",
            fontSize=18,
            leading=22,
            spaceAfter=18,
        ),
        "h1": ParagraphStyle(
            "H1",
            parent=base["Heading1"],
            fontName="Times-Bold",
            fontSize=13,
            leading=16,
            spaceBefore=12,
            spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["BodyText"],
            fontName="Times-Roman",
            fontSize=10.5,
            leading=14,
            spaceAfter=8,
        ),
        "small": ParagraphStyle(
            "Small",
            parent=base["BodyText"],
            fontName="Times-Italic",
            fontSize=9,
            leading=12,
            textColor=colors.grey,
        ),
    }


def _render(title: str, blocks: list[object]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
        title=title,
        author="PublicSector ADIP — Sample Corpus",
    )
    doc.build(blocks)
    return buf.getvalue()


# ---------- Document 1: Grant program announcement -------------------------------


def _grant_pdf() -> SamplePDF:
    s = _styles()
    blocks: list[object] = [
        Paragraph(
            "FY26 Resilient Communities Infrastructure Grant — "
            "Notice of Funding Opportunity",
            s["title"],
        ),
        Paragraph(
            "Federal Assistance Listing 97.139 &nbsp;·&nbsp; "
            "Issued by the Office of Resilience Programs",
            s["small"],
        ),
        Spacer(1, 12),
        Paragraph("1. Program Description", s["h1"]),
        Paragraph(
            "The Resilient Communities Infrastructure Grant (RCIG) supports "
            "state, local, tribal, and territorial governments in the design "
            "and construction of public infrastructure that reduces climate "
            "and seismic risk to populations of 50,000 or fewer. Eligible "
            "projects include hardening of water systems, undergrounding of "
            "distribution lines, and shoreline restoration measured against "
            "the 2024 federal coastal hazard atlas.",
            s["body"],
        ),
        Paragraph(
            "Funding under this announcement is non-competitive within "
            "designated disaster zones and competitive elsewhere. Applicants "
            "in disaster zones receive base allocations under §3.2; "
            "competitive applicants are scored against the criteria in §6.",
            s["body"],
        ),
        Paragraph("2. Award Information", s["h1"]),
        Paragraph(
            "Total program ceiling for fiscal year 2026 is $740,000,000. "
            "Individual awards range from $250,000 to $25,000,000 with a "
            "period of performance of up to 60 months. Cost-share is 25% "
            "non-federal for jurisdictions with a population over 25,000 and "
            "10% otherwise. Indirect costs are capped at the lesser of the "
            "applicant's federally negotiated indirect cost rate or 12%.",
            s["body"],
        ),
        Table(
            [
                ["Award Tier", "Min", "Max", "Cost-share"],
                ["Tier I — Planning", "$250,000", "$1,500,000", "10%"],
                ["Tier II — Design", "$1,500,001", "$8,000,000", "15%"],
                ["Tier III — Construction", "$8,000,001", "$25,000,000", "25%"],
            ],
            colWidths=[1.7 * inch, 1.1 * inch, 1.1 * inch, 1.1 * inch],
            style=TableStyle(
                [
                    ("FONT", (0, 0), (-1, -1), "Times-Roman", 9.5),
                    ("FONT", (0, 0), (-1, 0), "Times-Bold", 10),
                    ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.black),
                    ("LINEABOVE", (0, 0), (-1, 0), 0.75, colors.black),
                    ("LINEBELOW", (0, -1), (-1, -1), 0.5, colors.black),
                    ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                ]
            ),
        ),
        Spacer(1, 8),
        Paragraph("3. Eligibility", s["h1"]),
        Paragraph(
            "Eligible applicants are units of state, local, tribal, or "
            "territorial government with formal authority over the proposed "
            "project area. Nonprofit organizations may participate as "
            "subrecipients but cannot serve as the lead applicant. "
            "Jurisdictions placed on the GAO high-risk list in the prior "
            "fiscal year are categorically ineligible.",
            s["body"],
        ),
        Paragraph("4. Application Submission", s["h1"]),
        Paragraph(
            "Applications must be submitted through Grants.gov by 11:59 PM "
            "Eastern Time on February 28, 2026. Late or paper submissions "
            "will not be reviewed. The required application package includes "
            "the SF-424, project narrative (≤25 pages, 11pt Times New Roman, "
            "1\" margins), budget narrative, environmental review checklist, "
            "and a signed letter from the chief executive of the applicant "
            "jurisdiction.",
            s["body"],
        ),
        PageBreak(),
        Paragraph("5. Definitions", s["h1"]),
        Paragraph(
            "<b>Disaster zone</b> — a county or equivalent jurisdiction "
            "subject to a federally declared major disaster within the last "
            "36 months under 42 U.S.C. §5170.",
            s["body"],
        ),
        Paragraph(
            "<b>Resilience benefit</b> — the monetized expected reduction in "
            "annual loss from natural hazards, calculated under the FEMA "
            "Benefit-Cost Analysis Toolkit version 6.0 or later.",
            s["body"],
        ),
        Paragraph("6. Review and Selection Criteria", s["h1"]),
        Paragraph(
            "Competitive applications are scored on a 100-point scale: "
            "Project Need (30), Resilience Benefit (30), Organizational "
            "Capacity (20), Equity Plan (15), and Program Priorities (5). "
            "Applications scoring below 70 are not advanced to the "
            "programmatic review stage.",
            s["body"],
        ),
        Paragraph("7. Reporting Requirements", s["h1"]),
        Paragraph(
            "Quarterly performance reports are required during the period "
            "of performance, with annual financial reports due 90 days "
            "after the end of each federal fiscal year. A final close-out "
            "report is due 120 days after the end of the period of "
            "performance and must include audited construction completion "
            "documentation.",
            s["body"],
        ),
        Paragraph("8. Agency Contacts", s["h1"]),
        Paragraph(
            "Programmatic questions: program@resilience.example.gov. "
            "Grant administration: grants@resilience.example.gov. "
            "Hearing-impaired applicants may contact the Federal Relay "
            "Service at 800-877-8339.",
            s["body"],
        ),
    ]
    pdf = _render("FY26 Resilient Communities Infrastructure Grant", blocks)
    return SamplePDF(
        filename="fy26-resilient-communities-grant.pdf",
        title="FY26 Resilient Communities Infrastructure Grant",
        bytes_=pdf,
    )


# ---------- Document 2: Procurement notice ---------------------------------------


def _procurement_pdf() -> SamplePDF:
    s = _styles()
    blocks: list[object] = [
        Paragraph("Procurement Notice 2026-117", s["title"]),
        Paragraph(
            "Department of Transportation Services — "
            "Solicitation for Pavement Condition Assessment",
            s["small"],
        ),
        Spacer(1, 12),
        Paragraph("1. Purpose", s["h1"]),
        Paragraph(
            "The Department of Transportation Services seeks a qualified "
            "vendor to perform a pavement condition assessment on "
            "approximately 1,420 lane-miles of arterial roadway maintained "
            "by the Department. Deliverables include a roughness index "
            "report (IRI), a distress catalog conforming to the Distress "
            "Identification Manual (FHWA-RD-03-031), and a GIS package "
            "compatible with the Department's existing Esri ArcGIS "
            "Enterprise 11.x environment.",
            s["body"],
        ),
        Paragraph("2. Scope of Work", s["h1"]),
        Paragraph(
            "The contractor shall (a) complete data collection within 90 "
            "calendar days of notice-to-proceed using a vehicle-mounted "
            "high-resolution profiler and downward-facing imaging system, "
            "(b) deliver an interim QA report within 30 days of fieldwork "
            "completion, and (c) deliver final reports and GIS packages "
            "within 150 days of notice-to-proceed.",
            s["body"],
        ),
        Paragraph("3. Period of Performance", s["h1"]),
        Paragraph(
            "Performance shall begin no later than April 15, 2026 and end "
            "no later than November 30, 2026. No options are anticipated.",
            s["body"],
        ),
        Paragraph("4. Estimated Value", s["h1"]),
        Paragraph(
            "The estimated value is $1.8M – $2.4M firm fixed price, "
            "exclusive of any travel reimbursements which shall be billed "
            "at federal per diem rates.",
            s["body"],
        ),
        Paragraph("5. Submission Instructions", s["h1"]),
        Paragraph(
            "Proposals are due by 4:00 PM local time on March 18, 2026. "
            "Submissions shall be transmitted electronically through the "
            "Department's vendor portal. Proposals exceeding 40 pages "
            "(excluding required forms and appendices) will not be "
            "evaluated.",
            s["body"],
        ),
        Paragraph("6. Evaluation Factors", s["h1"]),
        Paragraph(
            "Award will be made on a best-value basis using the following "
            "factors, in descending order of importance: (1) Technical "
            "Approach, (2) Relevant Experience, (3) Key Personnel, (4) "
            "Price. Technical factors when combined are significantly more "
            "important than price; however, as technical scores converge "
            "price will become a more decisive factor.",
            s["body"],
        ),
        Paragraph("7. Set-Asides", s["h1"]),
        Paragraph(
            "This procurement is a 100% small business set-aside under "
            "NAICS 541370 (Surveying and Mapping Services), size standard "
            "$19.0M average annual receipts. Joint ventures must comply "
            "with 13 C.F.R. §125.8.",
            s["body"],
        ),
    ]
    pdf = _render("Procurement Notice 2026-117", blocks)
    return SamplePDF(
        filename="procurement-notice-2026-117.pdf",
        title="Procurement Notice 2026-117",
        bytes_=pdf,
    )


# ---------- Document 3: Policy memo ----------------------------------------------


def _policy_pdf() -> SamplePDF:
    s = _styles()
    blocks: list[object] = [
        Paragraph(
            "Memorandum: Implementation Guidance for the Modernized Public "
            "Records Disclosure Rule",
            s["title"],
        ),
        Paragraph(
            "From the Office of the General Counsel — for internal "
            "distribution to records officers and freedom-of-information "
            "liaisons.",
            s["small"],
        ),
        Spacer(1, 12),
        Paragraph("Background", s["h1"]),
        Paragraph(
            "The Modernized Public Records Disclosure Rule, codified at 5 "
            "C.F.R. Part 1840, took effect on January 1, 2026. The rule "
            "consolidates obligations previously distributed across several "
            "subject-matter regulations and adopts a uniform 20-business-day "
            "response window with a single 10-business-day extension for "
            "complex requests.",
            s["body"],
        ),
        Paragraph("Key Changes", s["h1"]),
        Paragraph(
            "First, fee waiver eligibility is now governed by a four-prong "
            "test that mirrors the federal FOIA standard at 5 U.S.C. "
            "§552(a)(4)(A)(iii). Second, agencies must publish a quarterly "
            "transparency report listing aggregate request volume, median "
            "response time, and exemption usage. Third, denials must "
            "include a Vaughn-style exemption index identifying the "
            "specific exemption applied to each withheld portion.",
            s["body"],
        ),
        Paragraph("Operational Impact", s["h1"]),
        Paragraph(
            "Records officers should expect a 12–18% increase in initial "
            "request volume during the first two quarters of 2026 driven "
            "by educational outreach campaigns. Pending requests filed "
            "before January 1, 2026 are governed by the prior rule unless "
            "the requester affirmatively elects in writing to proceed "
            "under the new rule.",
            s["body"],
        ),
        Paragraph("Implementation Timeline", s["h1"]),
        Paragraph(
            "By March 31, 2026 each subagency shall update its public "
            "records policy and post the updated policy at a stable URL. "
            "By June 30, 2026 each subagency shall complete training of "
            "all records officers and FOIA liaisons. The first quarterly "
            "transparency report covering Q1 2026 is due no later than "
            "May 15, 2026.",
            s["body"],
        ),
        Paragraph("Frequently Asked Questions", s["h1"]),
        Paragraph(
            "<b>Does the rule apply to draft documents?</b> Yes — drafts "
            "are subject to disclosure unless covered by the deliberative "
            "process exemption at §1840.305(d).",
            s["body"],
        ),
        Paragraph(
            "<b>What is the standard for redaction of personally "
            "identifiable information (PII)?</b> Apply the balancing test "
            "in §1840.310 and consult the Privacy Office before disclosing "
            "any document containing Social Security numbers, account "
            "numbers, or biometric identifiers.",
            s["body"],
        ),
        Paragraph(
            "<b>Are commercial requesters charged fees?</b> Yes — "
            "commercial requesters are charged search, review, and "
            "duplication fees at the rates published in §1840.405.",
            s["body"],
        ),
        Paragraph("Contact", s["h1"]),
        Paragraph(
            "Questions on this memorandum should be directed to "
            "records-policy@example.gov. Operational questions on a "
            "specific request should be directed to your assigned FOIA "
            "liaison.",
            s["body"],
        ),
    ]
    pdf = _render(
        "Implementation Guidance for the Modernized Public Records Disclosure Rule",
        blocks,
    )
    return SamplePDF(
        filename="policy-memo-public-records.pdf",
        title="Implementation Guidance for the Modernized Public Records Disclosure Rule",
        bytes_=pdf,
    )


def build_sample_pdfs() -> list[SamplePDF]:
    return [_grant_pdf(), _procurement_pdf(), _policy_pdf()]


def main() -> None:
    """CLI: write the corpus to ./sample-pdfs for inspection."""
    import os

    out = "sample-pdfs"
    os.makedirs(out, exist_ok=True)
    for sample in build_sample_pdfs():
        path = os.path.join(out, sample.filename)
        with open(path, "wb") as fh:
            fh.write(sample.bytes_)
        print(f"wrote {path} ({len(sample.bytes_):,} bytes)")


if __name__ == "__main__":
    main()
