version: '3.8'
services:
  graphql:
    build:
      context: ../node-graphql-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  fico:
    build:
      context: ../java-fico-integration
      dockerfile: Dockerfile  # (A Dockerfile for the Java service should be created)
    ports:
      - "8080:8080"

  mainframe:
    build:
      context: ../dotnet-mainframe-integration
      dockerfile: Dockerfile  # (A Dockerfile for the .NET service should be created)
    ports:
      - "6000:80"
