# circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Building C encryption module"
      - run:
          name: Build C Module
          command: |
            cd c-encryption
            make
      - run: echo "Running Python OCR Parser"
      - run:
          name: Run OCR Parser
          command: |
            cd ocr-parser
            pip install -r requirements.txt
            python ocr_parser.py sample_document.png || true
      - run: echo "Building Node.js Access Control Service"
      - run:
          name: Build Access Control
          command: |
            cd access-control
            npm install
      - run: echo "Building Java Document Indexer"
      - run:
          name: Build Document Indexer
          command: |
            cd document-indexer
            mvn clean package
      - run: echo "Building .NET API"
      - run:
          name: Build .NET API
          command: |
            cd api
            dotnet build
  compliance:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running compliance checks..."
      # Insert actual compliance and security tests here.

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - compliance
