"""Pydantic schemas for request/response models."""

from app.schemas.assignments import (
    AssignmentResponse,
    AssignmentsListResponse,
    CreateAssignmentRequest,
    CreateAssignmentResponse,
    UpdateAssignmentRequest,
    UpdateAssignmentResponse,
)
from app.schemas.auth import (
    AuthResponse,
    LoginRequest,
    MeResponse,
    RefreshRequest,
    RefreshResponse,
    RegisterRequest,
    TeamMembershipResponse,
    UserResponse,
)
from app.schemas.cycles import (
    ActiveCycleResponse,
    CreateCycleRequest,
    CreateCycleResponse,
    CycleResponse,
    CyclesListResponse,
)
from app.schemas.dashboards import (
    AssignmentSummary,
    ComplianceSummary,
    CycleInfo,
    DrilldownData,
    DueBucket,
    LeaderDashboardResponse,
    MemberDashboardResponse,
    MemberDrilldown,
    MemberPracticeDays,
    PrivateTicketAggregate,
    ProgressSummary,
    QuickLogDefaults,
    RiskSummary,
    SectionRisk,
    SongRisk,
    TicketDueSoon,
    TicketVisible,
    WeeklySummary,
)
from app.schemas.notification_preferences import (
    NotificationPreferencesResponse,
    NotificationPreferencesUpdate,
)
from app.schemas.practice_logs import (
    CreatePracticeLogRequest,
    CreatePracticeLogResponse,
    PracticeLogAssignmentResponse,
    PracticeLogResponse,
    PracticeLogsListResponse,
    SuggestedTicket,
    UpdatePracticeLogRequest,
    UpdatePracticeLogResponse,
)
from app.schemas.teams import (
    AcceptInviteRequest,
    AcceptInviteResponse,
    CreateInviteRequest,
    CreateInviteResponse,
    CreateTeamRequest,
    CreateTeamResponse,
    InvitePreviewResponse,
    MemberResponse,
    MembershipResponse,
    MembersListResponse,
    TeamResponse,
    UpdateMemberRequest,
    UpdateMemberResponse,
)
from app.schemas.tickets import (
    ClaimTicketResponse,
    CreateTicketRequest,
    CreateTicketResponse,
    TicketActivitiesResponse,
    TicketActivityResponse,
    TicketResponse,
    TicketsListResponse,
    TransitionTicketRequest,
    TransitionTicketResponse,
    UpdateTicketRequest,
    UpdateTicketResponse,
    VerifyTicketRequest,
    VerifyTicketResponse,
)

__all__ = [
    # Auth
    "RegisterRequest",
    "LoginRequest",
    "RefreshRequest",
    "RefreshResponse",
    "AuthResponse",
    "UserResponse",
    "TeamMembershipResponse",
    "MeResponse",
    # Teams
    "CreateTeamRequest",
    "CreateTeamResponse",
    "TeamResponse",
    "MemberResponse",
    "MembersListResponse",
    "UpdateMemberRequest",
    "UpdateMemberResponse",
    "MembershipResponse",
    # Invites
    "CreateInviteRequest",
    "CreateInviteResponse",
    "InvitePreviewResponse",
    "AcceptInviteRequest",
    "AcceptInviteResponse",
    # Cycles
    "CreateCycleRequest",
    "CreateCycleResponse",
    "CycleResponse",
    "CyclesListResponse",
    "ActiveCycleResponse",
    # Assignments
    "CreateAssignmentRequest",
    "CreateAssignmentResponse",
    "AssignmentResponse",
    "AssignmentsListResponse",
    "UpdateAssignmentRequest",
    "UpdateAssignmentResponse",
    # Practice Logs
    "CreatePracticeLogRequest",
    "CreatePracticeLogResponse",
    "PracticeLogResponse",
    "PracticeLogAssignmentResponse",
    "PracticeLogsListResponse",
    "SuggestedTicket",
    "UpdatePracticeLogRequest",
    "UpdatePracticeLogResponse",
    # Tickets
    "CreateTicketRequest",
    "CreateTicketResponse",
    "TicketResponse",
    "TicketsListResponse",
    "UpdateTicketRequest",
    "UpdateTicketResponse",
    "ClaimTicketResponse",
    "TicketActivityResponse",
    "TicketActivitiesResponse",
    "TransitionTicketRequest",
    "TransitionTicketResponse",
    "VerifyTicketRequest",
    "VerifyTicketResponse",
    # Dashboards
    "MemberDashboardResponse",
    "LeaderDashboardResponse",
    "CycleInfo",
    "AssignmentSummary",
    "TicketDueSoon",
    "QuickLogDefaults",
    "WeeklySummary",
    "ProgressSummary",
    "ComplianceSummary",
    "MemberPracticeDays",
    "RiskSummary",
    "SectionRisk",
    "SongRisk",
    "PrivateTicketAggregate",
    "DueBucket",
    "DrilldownData",
    "MemberDrilldown",
    "TicketVisible",
    # Notification Preferences
    "NotificationPreferencesResponse",
    "NotificationPreferencesUpdate",
]

