CC = gcc
CFLAGS = -Wall -O2

all: signature_validation

signature_validation: signature_validation.c
	$(CC) $(CFLAGS) -o signature_validation signature_validation.c

clean:
	rm -f signature_validation
