// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationsHub.Api.Data;

#nullable disable

namespace OperationsHub.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123012523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "BatchNumber")
                        .IsUnique();

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "B2401-001",
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialQuantity = 5000,
                            ManufactureDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            RemainingQuantity = 4500,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "B2402-002",
                            CreatedAt = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialQuantity = 3000,
                            ManufactureDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            RemainingQuantity = 3000,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "C2312-099",
                            CreatedAt = new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialQuantity = 10000,
                            ManufactureDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            RemainingQuantity = 8200,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 4,
                            BatchNumber = "P2403-FAIL",
                            CreatedAt = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialQuantity = 500,
                            ManufactureDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            RemainingQuantity = 500,
                            Status = "Quarantined"
                        });
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.ConfigSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ConfigSettings");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomerOrders");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.IntegrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IntegrationJobs");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.IntegrationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("IntegrationLogs");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.InventoryBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("InventoryBalances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Quantity = 4500,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastUpdatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 8000,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            LastUpdatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 200,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            LastUpdatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Quantity = 500,
                            WarehouseId = 3
                        });
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.InventoryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("InventoryLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A1-SHELF1-BIN1",
                            Description = "Main Floor, Aisle 1",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "A1-SHELF1-BIN2",
                            Description = "Main Floor, Aisle 1",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "EU-RECEIVING",
                            Description = "Receiving Dock",
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "EU-STORAGE-01",
                            Description = "Bulk Storage",
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "APAC-GENERAL",
                            Description = "General Storage",
                            WarehouseId = 3
                        });
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AllocatedWarehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShippedQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AllocatedWarehouseId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Vitamin",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Daily Multi-Vitamin (Men)",
                            Sku = "VIT-MULTI-001"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Vitamin",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Vitamin C 500mg",
                            Sku = "VIT-C-500"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Herbal Extract",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Organic Echinacea Tea",
                            Sku = "HERB-ECHIN"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pet Nutrition",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Canine Joint Support Chews",
                            Sku = "PET-JOINT"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sports Nutrition",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Whey Protein Isolate - Chocolate",
                            Sku = "PRO-WHEY-CHOC"
                        });
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.ReorderThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReorderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("ReorderThresholds");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.ReplenishmentSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedReorderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ReplenishmentSuggestions");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TEMPE-HQ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Tempe HQ",
                            Region = "US"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EU-HUB",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EU Hub",
                            Region = "EU"
                        },
                        new
                        {
                            Id = 3,
                            Code = "APAC-HUB",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "APAC Hub",
                            Region = "APAC"
                        });
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.Batch", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.IntegrationLog", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.IntegrationJob", "Job")
                        .WithMany("Logs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.InventoryBalance", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.Product", "Product")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationsHub.Api.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.InventoryLocation", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.InventoryMovement", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.InventoryLocation", "FromLocation")
                        .WithMany("MovementsFrom")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OperationsHub.Api.Models.Entities.Product", "Product")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OperationsHub.Api.Models.Entities.InventoryLocation", "ToLocation")
                        .WithMany("MovementsTo")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OperationsHub.Api.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromLocation");

                    b.Navigation("Product");

                    b.Navigation("ToLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.OrderLine", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.Warehouse", "AllocatedWarehouse")
                        .WithMany("OrderLines")
                        .HasForeignKey("AllocatedWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OperationsHub.Api.Models.Entities.CustomerOrder", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationsHub.Api.Models.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllocatedWarehouse");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.ReorderThreshold", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationsHub.Api.Models.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.ReplenishmentSuggestion", b =>
                {
                    b.HasOne("OperationsHub.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationsHub.Api.Models.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.CustomerOrder", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.IntegrationJob", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.InventoryLocation", b =>
                {
                    b.Navigation("MovementsFrom");

                    b.Navigation("MovementsTo");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("InventoryBalances");

                    b.Navigation("InventoryMovements");

                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("OperationsHub.Api.Models.Entities.Warehouse", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("InventoryLocations");

                    b.Navigation("InventoryMovements");

                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
